CREATE TABLE SYSTEM_INFORMATION (
 TYPE_CODE TEXT,
 INFO TEXT);
CREATE TABLE PARCEL (
 PARCEL_ID INTEGER NOT NULL,
 PARCEL_BASIS BLOB NOT NULL,
 ROAD_SHAPE BLOB,
 ROAD_NETWORK BLOB,
 BKGD BLOB,
 BKGD_AREA_CLS BLOB,
 MARK BLOB,
 ROAD_NAME BLOB,
 NAME BLOB,
 GUIDE BLOB,
 ROAD_DENSITY BLOB,
 ROAD_BASE_VERSION INTEGER,
 BKGD_BASE_VERSION INTEGER,
 PRIMARY KEY(PARCEL_ID));
CREATE INDEX [PARCEL_IDX01] ON [PARCEL] ([PARCEL_ID] ASC);
CREATE TABLE AREA_CLS (
 AREA_CLS6_CODE INTEGER NOT NULL,
 AREA_CLS5_CODE INTEGER NOT NULL,
 AREA_CLS4_CODE INTEGER NOT NULL,
 AREA_CLS3_CODE INTEGER NOT NULL,
 AREA_CLS2_CODE INTEGER NOT NULL,
 AREA_CLS1_CODE INTEGER NOT NULL,
 REGION_CODE TEXT,
 LAN_CD INTEGER NOT NULL,
 AREA_CLS_NAME TEXT NOT NULL,
 AREA_CLS_YOMI TEXT,
 PRIORITY_FLAG INTEGER NOT NULL,
 POSI_LATITUDE REAL,
 POSI_LONGITUDE REAL,
 ID  INTEGER NOT NULL,
 AREA_BASE_VERSION  INTEGER,
 PRIMARY KEY(AREA_CLS6_CODE,AREA_CLS5_CODE,AREA_CLS4_CODE,AREA_CLS3_CODE,AREA_CLS2_CODE,AREA_CLS1_CODE,LAN_CD,ID)
);
CREATE INDEX [Area_IDX01] ON [AREA_CLS] ([LAN_CD] ASC, [AREA_CLS1_CODE] ASC, [AREA_CLS2_CODE] ASC, [AREA_CLS3_CODE] ASC, [AREA_CLS4_CODE] ASC, [AREA_CLS5_CODE] ASC, [AREA_CLS6_CODE] ASC);
CREATE INDEX [Area_IDX02] ON [AREA_CLS] ([ID]);
CREATE INDEX [Area_IDX03] ON [AREA_CLS] ([AREA_CLS3_CODE] ASC , [AREA_CLS4_CODE] ASC , [AREA_CLS5_CODE] ASC , [AREA_CLS6_CODE] ASC , [AREA_CLS2_CODE] ASC);
CREATE TABLE DOWNLOAD_AREA_MAP (
 ID INTEGER NOT NULL,
 KIND TEXT NOT NULL,
 COUNTRY_CODE INTEGER,
 DISPLAY_NUM INTEGER NOT NULL,
 COUNTRY_NAME TEXT,
 AREA_GROUP TEXT,
 AREA_NAME TEXT NOT NULL,
 DOWNLOAD_FLAG INTEGER NOT NULL,
 BASE_VERSION INTEGER,
 NOTE TEXT,
 PRIMARY KEY(ID,KIND));
CREATE INDEX [DOWNLOAD_AREA_MAP_IDX01] ON [DOWNLOAD_AREA_MAP] ([ID] ASC,[KIND] ASC);
CREATE TABLE DOWNLOAD_BASE_VERSION (
 KIND TEXT NOT NULL,
 TABLE_NAME TEXT NOT NULL,
 DOWNLOAD_FLAG INTEGER NOT NULL,
 BASE_VERSION INTEGER,
 NOTE TEXT,
 PRIMARY KEY(KIND,TABLE_NAME));
CREATE INDEX [DOWNLOAD_BASE_VERSION_IDX01] ON [DOWNLOAD_BASE_VERSION] ([KIND] ASC,[TABLE_NAME] ASC);
CREATE TABLE DOWNLOAD_SYS (
 KIND TEXT NOT NULL,
 NAME TEXT NOT NULL,
 VERSION INTEGER NOT NULL,
 PRIMARY KEY(KIND));
CREATE INDEX [DOWNLOAD_SYS_IDX01] ON [DOWNLOAD_SYS] ([KIND] ASC);
